// <auto-generated />
using DiveDeepProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeepProject.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    [Migration("20250916092617_Unavailable")]
    partial class Unavailable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeepProject.Models.Domain.BCD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("BCDs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Navigator Lite BCD",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Model = "BCD Glide",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Model = "BCD Hydros Pro",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            Model = "BCD Modular",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.DivingSuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DivingSuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = 0,
                            Model = "Definition",
                            ProductId = 5,
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 2,
                            Gender = 0,
                            Model = "Definition",
                            ProductId = 6,
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 3,
                            Gender = 0,
                            Model = "Definition",
                            ProductId = 7,
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 4,
                            Gender = 0,
                            Model = "W5",
                            ProductId = 8,
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 5,
                            Gender = 0,
                            Model = "Proteus",
                            ProductId = 9,
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 6,
                            Gender = 0,
                            Model = "Exodry 4.0",
                            ProductId = 10,
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 7,
                            Gender = 0,
                            Model = "D7 Evo",
                            ProductId = 11,
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 8,
                            Gender = 0,
                            Model = "E.Lite Plus",
                            ProductId = 12,
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Flipper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Flippers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Jet Fin",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 2,
                            Model = "GO Travel",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 3,
                            Model = "Seawing Supernova",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 4,
                            Model = "Propulsion",
                            ProductId = 30
                        },
                        new
                        {
                            Id = 5,
                            Model = "ALA",
                            ProductId = 31
                        },
                        new
                        {
                            Id = 6,
                            Model = "Tech",
                            ProductId = 32
                        },
                        new
                        {
                            Id = 7,
                            Model = "Rec Fin",
                            ProductId = 33
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<string>("UnavailableDates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 125.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 140.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 200.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Seac",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 145.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Scubapro",
                            Description = "3 mm wetsuit for warm water diving.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 100.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Scubapro",
                            Description = "5 mm wetsuit for versatile diving.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 100.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Scubapro",
                            Description = "7 mm wetsuit for colder waters.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 100.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Waterproof",
                            Description = "3.5 mm wetsuit, flexible and warm.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 100.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Fourth Element",
                            Description = "5 mm premium wetsuit.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 120.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Scubapro",
                            Description = "Durable drysuit.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 300.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Waterproof",
                            Description = "Advanced drysuit for technical diving.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 320.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Santi",
                            Description = "Top-tier drysuit for professionals.",
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            PricePerDay = 350.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Scubapro",
                            Description = "Compact tank, good for short dives.",
                            ImagePath = "lib/Public/TankProduct.png",
                            PricePerDay = 150.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Scubapro",
                            Description = "Standard tank for recreational diving.",
                            ImagePath = "lib/Public/TankProduct.png",
                            PricePerDay = 160.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Scubapro",
                            Description = "Versatile tank, good for most dives.",
                            ImagePath = "lib/Public/TankProduct.png",
                            PricePerDay = 170.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Scubapro",
                            Description = "Large tank for extended dives.",
                            ImagePath = "lib/Public/TankProduct.png",
                            PricePerDay = 180.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Scubapro",
                            Description = "High performance regulator.",
                            ImagePath = "lib/Public/RegulatorSetProduct.png",
                            PricePerDay = 125.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Scubapro",
                            Description = "Reliable regulator set.",
                            ImagePath = "lib/Public/RegulatorSetProduct.png",
                            PricePerDay = 100.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Scubapro",
                            Description = "Top-tier regulator with carbon second stage.",
                            ImagePath = "lib/Public/RegulatorSetProduct.png",
                            PricePerDay = 150.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Scubapro",
                            Description = "Frameless mask with wide view.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 50.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Scubapro",
                            Description = "Premium diving mask.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 60.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Scubapro",
                            Description = "Compact mask for smaller faces.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 50.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Scubapro",
                            Description = "Wide field of view mask.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 75.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Fourth Element",
                            Description = "Advanced mask for all conditions.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 75.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Fourth Element",
                            Description = "High clarity mask.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 75.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Tusa",
                            Description = "Durable and clear diving mask.",
                            ImagePath = "lib/Public/MaskProduct.png",
                            PricePerDay = 75.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Scubapro",
                            Description = "Classic durable fin.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 50.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Scubapro",
                            Description = "Lightweight travel fin.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 50.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Scubapro",
                            Description = "High performance split fin.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 60.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Seac",
                            Description = "Durable and powerful fin.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 50.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Seac",
                            Description = "Compact and flexible fin.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 50.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Fourth Element",
                            Description = "Strong fin for technical diving.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 75.0,
                            UnavailableDates = "[]"
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Fourth Element",
                            Description = "All-round recreational fin.",
                            ImagePath = "lib/Public/FinsProduct.png",
                            PricePerDay = 80.0,
                            UnavailableDates = "[]"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Regulatorset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SecondStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Regulatorsets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstStep = "MK25EVO",
                            Octopus = "R105",
                            ProductId = 17,
                            SecondStep = "S600"
                        },
                        new
                        {
                            Id = 2,
                            FirstStep = "MK17EVO",
                            Octopus = "R095",
                            ProductId = 18,
                            SecondStep = "C370"
                        },
                        new
                        {
                            Id = 3,
                            FirstStep = "MK25EVO BT",
                            Octopus = "S270",
                            ProductId = 19,
                            SecondStep = "A700 Carbon BT"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.SnorkelSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SnorkelSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Ghost",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 2,
                            Model = "D-Mask",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 3,
                            Model = "Spectra Mini",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 4,
                            Model = "Crystal VU",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 5,
                            Model = "Scout Kontrast",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 6,
                            Model = "Scout Enhance",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 7,
                            Model = "Element",
                            ProductId = 26
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 13,
                            Volume = "5 L"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 14,
                            Volume = "10 L"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 15,
                            Volume = "12 L"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 16,
                            Volume = "15 L"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.BCD", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("BCDs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.DivingSuit", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("DivingSuits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Flipper", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("Flippers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Regulatorset", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("Regulatorsets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.SnorkelSet", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("SnorkelSets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Tank", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("Tanks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.Navigation("BCDs");

                    b.Navigation("DivingSuits");

                    b.Navigation("Flippers");

                    b.Navigation("Regulatorsets");

                    b.Navigation("SnorkelSets");

                    b.Navigation("Tanks");
                });
#pragma warning restore 612, 618
        }
    }
}
