// <auto-generated />
using System;
using DiveDeepProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeepProject.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    [Migration("20250912124053_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeepProject.Models.Domain.BCD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("BCDs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Navigator Lite BCD",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Model = "BCD Glide",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Model = "BCD Hydros Pro",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            Model = "BCD Modular",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("DivingSuitId")
                        .HasColumnType("int");

                    b.Property<int?>("FlipperId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<int?>("RegulatorsetId")
                        .HasColumnType("int");

                    b.Property<int?>("SnorkelSetId")
                        .HasColumnType("int");

                    b.Property<int?>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivingSuitId");

                    b.HasIndex("FlipperId");

                    b.HasIndex("RegulatorsetId");

                    b.HasIndex("SnorkelSetId");

                    b.HasIndex("TankId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 125.0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 140.0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 200.0
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Seac",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            ImagePath = "lib/Public/BCDProduct.png",
                            PricePerDay = 145.0
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.DivingSuit", b =>
                {
                    b.HasBaseType("DiveDeepProject.Models.Domain.Product");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Model")
                                .HasColumnName("DivingSuit_Model");

                            t.Property("Size")
                                .HasColumnName("DivingSuit_Size");
                        });

                    b.HasDiscriminator().HasValue("DivingSuit");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Flipper", b =>
                {
                    b.HasBaseType("DiveDeepProject.Models.Domain.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Flipper");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Regulatorset", b =>
                {
                    b.HasBaseType("DiveDeepProject.Models.Domain.Product");

                    b.Property<string>("FirstStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Regulatorset");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.SnorkelSet", b =>
                {
                    b.HasBaseType("DiveDeepProject.Models.Domain.Product");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Model")
                                .HasColumnName("SnorkelSet_Model");
                        });

                    b.HasDiscriminator().HasValue("SnorkelSet");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Tank", b =>
                {
                    b.HasBaseType("DiveDeepProject.Models.Domain.Product");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tank");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.BCD", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("BCDs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.DivingSuit", null)
                        .WithMany("Products")
                        .HasForeignKey("DivingSuitId");

                    b.HasOne("DiveDeepProject.Models.Domain.Flipper", null)
                        .WithMany("Products")
                        .HasForeignKey("FlipperId");

                    b.HasOne("DiveDeepProject.Models.Domain.Regulatorset", null)
                        .WithMany("Products")
                        .HasForeignKey("RegulatorsetId");

                    b.HasOne("DiveDeepProject.Models.Domain.SnorkelSet", null)
                        .WithMany("Products")
                        .HasForeignKey("SnorkelSetId");

                    b.HasOne("DiveDeepProject.Models.Domain.Tank", null)
                        .WithMany("Products")
                        .HasForeignKey("TankId");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.Navigation("BCDs");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.DivingSuit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Flipper", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Regulatorset", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.SnorkelSet", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Tank", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
