// <auto-generated />
using System;
using DiveDeepProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiveDeepProject.Migrations
{
    [DbContext(typeof(DiveDeepContext))]
    [Migration("20250930074525_den")]
    partial class den
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiveDeepProject.Models.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.BCD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("BCDs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Navigator Lite BCD",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Model = "BCD Glide",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Model = "BCD Hydros Pro",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            Model = "BCD Modular",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nicklas Hus",
                            City = "Nicklas By",
                            Email = "Nicklas@gmail.com",
                            Name = "Nicklas Lover boy",
                            PhoneNumber = "1-800-LoverBoy",
                            ZipCode = "3500"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.DivingSuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Thickness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DivingSuits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = 0,
                            Model = "Definition",
                            ProductId = 5,
                            Thickness = "3 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 2,
                            Gender = 0,
                            Model = "Definition",
                            ProductId = 6,
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 3,
                            Gender = 0,
                            Model = "Definition",
                            ProductId = 7,
                            Thickness = "7 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 4,
                            Gender = 0,
                            Model = "W5",
                            ProductId = 8,
                            Thickness = "3.5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 5,
                            Gender = 0,
                            Model = "Proteus",
                            ProductId = 9,
                            Thickness = "5 mm",
                            Type = "Våddragt"
                        },
                        new
                        {
                            Id = 6,
                            Gender = 0,
                            Model = "Exodry 4.0",
                            ProductId = 10,
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 7,
                            Gender = 0,
                            Model = "D7 Evo",
                            ProductId = 11,
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        },
                        new
                        {
                            Id = 8,
                            Gender = 0,
                            Model = "E.Lite Plus",
                            ProductId = 12,
                            Thickness = "N/A",
                            Type = "Tørdragt"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Flipper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Flippers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Jet Fin",
                            ProductId = 27
                        },
                        new
                        {
                            Id = 2,
                            Model = "GO Travel",
                            ProductId = 28
                        },
                        new
                        {
                            Id = 3,
                            Model = "Seawing Supernova",
                            ProductId = 29
                        },
                        new
                        {
                            Id = 4,
                            Model = "Propulsion",
                            ProductId = 30
                        },
                        new
                        {
                            Id = 5,
                            Model = "ALA",
                            ProductId = 31
                        },
                        new
                        {
                            Id = 6,
                            Model = "Tech",
                            ProductId = 32
                        },
                        new
                        {
                            Id = 7,
                            Model = "Rec Fin",
                            ProductId = 33
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackageID")
                        .HasColumnType("int");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PackageID");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/BCDProduct.png",
                            Model = "Navigator Lite BCD",
                            PricePerDay = 125.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/BCDProduct.png",
                            Model = "BCD Glide",
                            PricePerDay = 140.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Scubapro",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/BCDProduct.png",
                            Model = "BCD Hydros Pro",
                            PricePerDay = 200.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Seac",
                            Description = "Comfortable and durable BCD for all diving levels.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/BCDProduct.png",
                            Model = "BCD Modular",
                            PricePerDay = 145.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Scubapro",
                            Description = "3 mm wetsuit for warm water diving.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "Definition",
                            PricePerDay = 100.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Scubapro",
                            Description = "5 mm wetsuit for versatile diving.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "Definition",
                            PricePerDay = 100.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Scubapro",
                            Description = "7 mm wetsuit for colder waters.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "Definition",
                            PricePerDay = 100.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Waterproof",
                            Description = "3.5 mm wetsuit, flexible and warm.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "W5",
                            PricePerDay = 100.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Fourth Element",
                            Description = "5 mm premium wetsuit.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "Proteus",
                            PricePerDay = 120.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Scubapro",
                            Description = "Durable drysuit.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "Exodry 4.0",
                            PricePerDay = 300.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Waterproof",
                            Description = "Advanced drysuit for technical diving.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "D7 Evo",
                            PricePerDay = 320.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Santi",
                            Description = "Top-tier drysuit for professionals.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/DivingSuitProduct.png",
                            Model = "E.Lite Plus",
                            PricePerDay = 350.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Scubapro",
                            Description = "Compact tank, good for short dives.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/TankProduct.png",
                            Model = "",
                            PricePerDay = 150.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Scubapro",
                            Description = "Standard tank for recreational diving.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/TankProduct.png",
                            Model = "",
                            PricePerDay = 160.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Scubapro",
                            Description = "Versatile tank, good for most dives.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/TankProduct.png",
                            Model = "",
                            PricePerDay = 170.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Scubapro",
                            Description = "Large tank for extended dives.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/TankProduct.png",
                            Model = "",
                            PricePerDay = 180.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Scubapro",
                            Description = "High performance regulator.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/RegulatorSetProduct.png",
                            Model = "MK25EVO",
                            PricePerDay = 125.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Scubapro",
                            Description = "Reliable regulator set.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/RegulatorSetProduct.png",
                            Model = "MK17EVO",
                            PricePerDay = 100.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Scubapro",
                            Description = "Top-tier regulator with carbon second stage.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/RegulatorSetProduct.png",
                            Model = "MK25EVO BT",
                            PricePerDay = 150.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Scubapro",
                            Description = "Frameless mask with wide view.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "Ghost",
                            PricePerDay = 50.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Scubapro",
                            Description = "Premium diving mask.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "D-Mask",
                            PricePerDay = 60.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Scubapro",
                            Description = "Compact mask for smaller faces.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "Spectra Mini",
                            PricePerDay = 50.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Scubapro",
                            Description = "Wide field of view mask.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "Crystal VU",
                            PricePerDay = 75.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Fourth Element",
                            Description = "Advanced mask for all conditions.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "Scout Kontrast",
                            PricePerDay = 75.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Fourth Element",
                            Description = "High clarity mask.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "Scout Enhance",
                            PricePerDay = 75.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Tusa",
                            Description = "Durable and clear diving mask.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/MaskProduct.png",
                            Model = "Element",
                            PricePerDay = 75.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Scubapro",
                            Description = "Classic durable fin.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "Jet Fin",
                            PricePerDay = 50.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Scubapro",
                            Description = "Lightweight travel fin.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "GO Travel",
                            PricePerDay = 50.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 29,
                            Brand = "Scubapro",
                            Description = "High performance split fin.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "Seawing Supernova",
                            PricePerDay = 60.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Seac",
                            Description = "Durable and powerful fin.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "Propulsion",
                            PricePerDay = 50.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Seac",
                            Description = "Compact and flexible fin.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "ALA",
                            PricePerDay = 50.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Fourth Element",
                            Description = "Strong fin for technical diving.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "Tech",
                            PricePerDay = 75.0,
                            StartDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Fourth Element",
                            Description = "All-round recreational fin.",
                            EndDate = new DateOnly(1, 1, 1),
                            ImagePath = "lib/Public/FinsProduct.png",
                            Model = "Rec Fin",
                            PricePerDay = 80.0,
                            StartDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptedTerms")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("HasDivingCertificat")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedTerms = false,
                            Comment = "First receipt",
                            CustomerId = 1,
                            HasDivingCertificat = false,
                            PickupDate = new DateTime(2025, 9, 30, 9, 45, 25, 137, DateTimeKind.Local).AddTicks(5340),
                            ReturnDate = new DateTime(2025, 10, 7, 9, 45, 25, 137, DateTimeKind.Local).AddTicks(5381),
                            Total = 500.0
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Regulatorset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SecondStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Regulatorsets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstStep = "MK25EVO",
                            Octopus = "R105",
                            ProductId = 17,
                            SecondStep = "S600"
                        },
                        new
                        {
                            Id = 2,
                            FirstStep = "MK17EVO",
                            Octopus = "R095",
                            ProductId = 18,
                            SecondStep = "C370"
                        },
                        new
                        {
                            Id = 3,
                            FirstStep = "MK25EVO BT",
                            Octopus = "S270",
                            ProductId = 19,
                            SecondStep = "A700 Carbon BT"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.SnorkelSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SnorkelSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Ghost",
                            ProductId = 20
                        },
                        new
                        {
                            Id = 2,
                            Model = "D-Mask",
                            ProductId = 21
                        },
                        new
                        {
                            Id = 3,
                            Model = "Spectra Mini",
                            ProductId = 22
                        },
                        new
                        {
                            Id = 4,
                            Model = "Crystal VU",
                            ProductId = 23
                        },
                        new
                        {
                            Id = 5,
                            Model = "Scout Kontrast",
                            ProductId = 24
                        },
                        new
                        {
                            Id = 6,
                            Model = "Scout Enhance",
                            ProductId = 25
                        },
                        new
                        {
                            Id = 7,
                            Model = "Element",
                            ProductId = 26
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 13,
                            Volume = "5 L"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 14,
                            Volume = "10 L"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 15,
                            Volume = "12 L"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 16,
                            Volume = "15 L"
                        });
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.UnavailableDates", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UnavailableDate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.HasIndex("ProductId");

                    b.ToTable("UnavailableDates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PackageReceipt", b =>
                {
                    b.Property<int>("PackagesId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptsId")
                        .HasColumnType("int");

                    b.HasKey("PackagesId", "ReceiptsId");

                    b.HasIndex("ReceiptsId");

                    b.ToTable("ReceiptPackage", (string)null);
                });

            modelBuilder.Entity("ProductReceipt", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "ReceiptsId");

                    b.HasIndex("ReceiptsId");

                    b.ToTable("ReceiptProduct", (string)null);
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.BCD", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("BCDs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Customer", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.ApplicationUser", "User")
                        .WithOne("Customer")
                        .HasForeignKey("DiveDeepProject.Models.Domain.Customer", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.DivingSuit", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("DivingSuits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Flipper", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("Flippers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Package", "Package")
                        .WithMany("Products")
                        .HasForeignKey("PackageID");

                    b.HasOne("DiveDeepProject.Models.Domain.ApplicationUser", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Receipt", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Customer", "Customer")
                        .WithMany("Receipts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Regulatorset", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("Regulatorsets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.SnorkelSet", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("SnorkelSets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Tank", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", "Product")
                        .WithMany("Tanks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.UnavailableDates", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", null)
                        .WithMany("UnavailableDates")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeepProject.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackageReceipt", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeepProject.Models.Domain.Receipt", null)
                        .WithMany()
                        .HasForeignKey("ReceiptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductReceipt", b =>
                {
                    b.HasOne("DiveDeepProject.Models.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiveDeepProject.Models.Domain.Receipt", null)
                        .WithMany()
                        .HasForeignKey("ReceiptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.ApplicationUser", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Customer", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Package", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DiveDeepProject.Models.Domain.Product", b =>
                {
                    b.Navigation("BCDs");

                    b.Navigation("DivingSuits");

                    b.Navigation("Flippers");

                    b.Navigation("Regulatorsets");

                    b.Navigation("SnorkelSets");

                    b.Navigation("Tanks");

                    b.Navigation("UnavailableDates");
                });
#pragma warning restore 612, 618
        }
    }
}
