<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\lib\Public\BCD.png" />
    <Content Remove="wwwroot\lib\Public\DesignImageTemplate.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="wwwroot\lib\Public\BCD.png" />
    <Resource Include="wwwroot\lib\Public\DesignImageTemplate.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\lib\Public\LOGO.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
